using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MonkeyLoader.Events
{
    /// <summary>
    /// Delegate for the <see cref="IEventSource{TEvent, TTarget}.Dispatching"/> event.
    /// </summary>
    /// <typeparam name="TEvent">The type representing the async event arguments.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the async event.</typeparam>
    /// <param name="eventData">An object containing all the relevant information for the async event.</param>
    public delegate Task AsyncEventDispatching<in TEvent, in TTarget>(TEvent eventData)
        where TEvent : class, IAsyncEvent<TTarget>;

    /// <summary>
    /// Delegate for the <see cref="ICancelableAsyncEventSource{TEvent, TTarget}.Dispatching"/> event.
    /// </summary>
    /// <typeparam name="TEvent">The type representing the cancelable async event arguments.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the cancelable async event.</typeparam>
    /// <param name="eventData">An object containing all the relevant information for the async event, including canceling the action.</param>
    public delegate Task CancelableAsyncEventDispatching<in TEvent, in TTarget>(TEvent eventData)
        where TEvent : class, ICancelableAsyncEvent<TTarget>;

    /// <summary>
    /// Defines the interface for sources of a certain type of async events.
    /// </summary>
    /// <typeparam name="TEvent">The type of async events generated by this source.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the async event.</typeparam>
    public interface IAsyncEventSource<out TEvent, out TTarget> where TEvent : class, IAsyncEvent<TTarget>
    {
        /// <summary>
        /// Needs to be invoked when an event is generated with a new instance of <typeparamref href="TEvent"/>.
        /// </summary>
        public event AsyncEventDispatching<TEvent, TTarget>? Dispatching;
    }

    /// <summary>
    /// Defines the interface for sources of a certain type of cancelable async events.
    /// </summary>
    /// <typeparam name="TEvent">The type of cancelable async events generated by this source.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the async events.</typeparam>
    public interface ICancelableAsyncEventSource<out TEvent, out TTarget> where TEvent : class, ICancelableAsyncEvent<TTarget>
    {
        /// <summary>
        /// Needs to be invoked when an event is generated with a new instance of the cancelable <typeparamref href="TEvent"/>.
        /// </summary>
        /// <remarks>
        /// When the event's <see cref="ICancelableAsyncEvent{TTarget}.Canceled">Canceled</see>
        /// property is <c>true</c>, the default action should be prevented from happening.
        /// </remarks>
        public event CancelableAsyncEventDispatching<TEvent, TTarget>? Dispatching;
    }
}