using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MonkeyLoader.Events
{
    /// <summary>
    /// Delegate for the <see cref="ICancelableEventSource{TEvent, TTarget}.Dispatching"/> event.
    /// </summary>
    /// <typeparam name="TEvent">The type representing the event arguments.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the events.</typeparam>
    /// <param name="eventData">An object containing all the relevant information for the events, including canceling the action.</param>
    public delegate void CancelableEventDispatching<in TEvent, in TTarget>(TEvent eventData)
        where TEvent : class, ICancelableEvent<TTarget>;

    /// <summary>
    /// Delegate for the <see cref="IEventSource{TEvent, TTarget}.Dispatching"/> event.
    /// </summary>
    /// <typeparam name="TEvent">The type representing the event arguments.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the events.</typeparam>
    /// <param name="eventData">An object containing all the relevant information for the events.</param>
    public delegate void EventDispatching<in TEvent, in TTarget>(TEvent eventData)
        where TEvent : class, IEvent<TTarget>;

    /// <summary>
    /// Defines the interface for sources of a certain type of cancelable events.
    /// </summary>
    /// <typeparam name="TEvent">The type of cancelable events generated by this source.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the events.</typeparam>
    public interface ICancelableEventSource<out TEvent, out TTarget> where TEvent : class, ICancelableEvent<TTarget>
    {
        /// <summary>
        /// Needs to be invoked when an event is generated with a new instance of the cancelable <typeparamref href="TEvent"/>.
        /// </summary>
        /// <remarks>
        /// When the event's <see cref="ICancelableEvent{TTarget}.Canceled">Canceled</see>
        /// property is <c>true</c>, the default action should be prevented from happening.
        /// </remarks>
        public event CancelableEventDispatching<TEvent, TTarget> Dispatching;
    }

    /// <summary>
    /// Defines the interface for sources of a certain type of events.
    /// </summary>
    /// <typeparam name="TEvent">The type of events generated by this source.</typeparam>
    /// <typeparam name="TTarget">The type of the target objects that are the focus of the events.</typeparam>
    public interface IEventSource<out TEvent, out TTarget> where TEvent : class, IEvent<TTarget>
    {
        /// <summary>
        /// Needs to be invoked when an event is generated with a new instance of <typeparamref href="TEvent"/>.
        /// </summary>
        public event EventDispatching<TEvent, TTarget> Dispatching;
    }
}